import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import FormComponent from '../components/formComponent'
import Description from '@/components/description'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Delivery Cost | DEW</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.main}>
      <div className={inter.className}>
        <div className={styles.wrapper}>
        <div className={styles.header}>
          <a href="https://deweloper.fi" title='Link to my website'>
          <img src="/favicon.svg" alt="logo" width="36"/>
          </a>
            <h1>Calculate your orders delivery cost.</h1>
        </div>
          <div className={styles.grid}>
            <FormComponent/>
            <Description/>
          </div>
        </div>
      </div>
        
      </main>
    </>

  )
}

